### ISSUE TITLE
[Feat] 회원가입 단계별 UI 구현

### ISSUE THREAD

**Issue by ehanadul** [Int-one/DDogDog#104]
## 💡 Feature Issue

* 회원가입 단계별 UI를 통일된 디자인으로 구현 

## 🌿 To-do

- [ ] 이메일 입력 페이지 UI 개선
- [ ] 비밀번호, 닉네임, 전화번호 입력 페이지 UI 통일
- [ ] 생년월일 및 성별 입력 페이지: 성별 선택 버튼 구현
- [ ] 신장 및 체중 입력 페이지: 데이터 입력 필드 디자인 변경 및 마우스 휠 조정 기능 구현
- [ ] 위치 정보 확인 페이지: 지도 표시 및 위치 확인
- [ ] 회원 정보 확인 페이지: 테이블 형태의 정보 정리 및 UI 개선
