### ISSUE TITLE
[Feat] 반려견 등록, 도그워커 가입 페이지 UI 개선

### ISSUE THREAD

**Issue by ehanadul** [Int-one/DDogDog#106]
## 💡 Feature Issue
반려견 등록 페이지와 도그워커 가입 관련 UI를 기존 스타일과 통일되게 개선

## 🌿 To-do
- [ ] 반려견 등록 페이지 UI 수정
  - [ ] 뒤로가기 버튼 추가 및 위치 조정
  - [ ] 입력 필드와 버튼 스타일 통일
  - [ ] 세로 스크롤 활성화
  - [ ] 안내 메시지 추가
- [ ] 도그워커 가입 페이지 UI 수정
  - [ ] 약관 체크박스 스타일 개선
  - [ ] 페이지 상단 뒤로가기 버튼 추가
  - [ ] 약관 체크박스 및 전체 동의 버튼 스타일 통일
- [ ] 도그워커 프로필 작성 페이지 UI 수정
  - [ ] 입력 필드 및 버튼 스타일 개선
  - [ ] 안내 메시지 스타일 추가
  - [ ] 회원가입 페이지와 유사한 레이아웃 및 디자인 적용
