### ISSUE TITLE
[Feat] 사용자 위치정보 확인 및 인증 로직 구현

### ISSUE THREAD

**Issue by ehanadul** [Int-one/DDogDog#36]
## 💡 Feature Issue

- 로그인 시 사용자 지역 정보를 로컬스토리지에 저장
- 회원가입 시 위치 정보를 확인하고 인증하는 로직 구현

## 🌿 To-do

- [ ] 로그인 시 사용자 지역 정보 로컬스토리지에 저장
  - [ ] 백엔드에서 사용자 지역 정보 제공
  - [ ] 로그인 성공 시 로컬스토리지에 저장
- [ ] 회원가입 위치 정보 인증 로직 구현
  - [ ] 사용자 위치를 Kakao 지도 API로 가져오기
  - [ ] 주소를 '읍/면/동'까지만 저장
  - [ ] 사용자 인증 여부 확인 로직 추가
