### ISSUE TITLE
[Feat] 산책페이지 구현

### ISSUE THREAD

**Issue by Eric4848** [Int-one/DDogDog#38]
## 💡 Feature Issue

산책 페이지를 피그마에서 계획한대로 수정
## 🌿  To-do

- [ ] 누적, 월간, 주간별 구현
- [ ] 산책 기록 정보 구현
- [ ] 반려견 정보를 가지고와서 같이 산책할 반려견 선택기능 구현
