### ISSUE TITLE
[Feat] 하단 메뉴바 컴포넌트 구현

### ISSUE THREAD

**Issue by ehanadul** [Int-one/DDogDog#42]
## 💡 Feature Issue
하단 고정된 메뉴바 컴포넌트 생성 및 각 메뉴 이동 기능 구현

- 모바일 화면(360x780) 기반 웹앱 형식으로 구성
- 하단 메뉴바는 5개의 메뉴로 구성되며, 각 메뉴 클릭 시 해당 페이지로 이동
- 선택된 메뉴의 아이콘과 텍스트 색상을 변경하여 현재 페이지를 표시

## 🌿  To-do
- [ ] 하단 메뉴바 컴포넌트 생성
- [ ] 각 메뉴에 아이콘 및 텍스트 추가
- [ ] 메뉴 클릭 시 해당 페이지로 라우팅
- [ ] 선택된 메뉴 색상 강조 (아이콘 및 텍스트 색상 변경)
- [ ] Flexbox를 활용한 동일한 간격 및 중앙 정렬 구현
