### ISSUE TITLE
[Fix] router 경로 오류 수정

### ISSUE THREAD

**Issue by ehanadul** [Int-one/DDogDog#48]
## 💡 Fix Issue
- 메인 페이지를 `/`, 로그인 페이지를 `/login`으로 경로 수정
- 관련 경로 수정 및 연결 작업

## 🌿  To-do
- [ ] 메인 페이지 경로 변경 `/`
- [ ] 로그인 페이지 경로 변경 `/login`
- [ ] 각 관련 컴포넌트 및 뷰 파일 경로 수정
- [ ] 기존 경로에서 새 경로로의 연결 확인
