### ISSUE TITLE
[Feat] ERD 변경사항 반영 및 API 추가

### ISSUE THREAD

**Issue by Eric4848** [Int-one/DDogDog#5]
## 💡 Feature Issue

프로젝트를 진행하며 수정된 ERD에 맞게 DB 및 DTO 변경, 유저의 가장 최근 산책 기록, 최근 산책 기록 API 생성 필요

## 🌿  To-do

- [x] DB의 컬럼명 변경
- [x] 변경된 컬렴명에 맞게 더미 데이터 수정하며 user_id는 email형식에 맞도록 생성
- [x] user_id를 이용해 가장 최근 산책 기록을 반환하는 API 생성
- [x] 전체 유저의 갖아 최근 산책 기록 10개를 반환하는 API 생성
