### ISSUE TITLE
[Feat] 산책 탭 메인화면

### ISSUE THREAD

**Issue by Eric4848** [Int-one/DDogDog#50]
## 💡 Feature Issue

산책 탭 메인화면을 구성
## 🌿  To-do

- [ ] 대기중인 반려견을 맨 위로 보내기
- [ ] 산책에 필요한 준비물 체크리스트 만들기
- [ ] 나의 산책기록 요약하여 보여주기
- [ ] 산책 가기 버튼을 구현
