### ISSUE TITLE
[Feat] PetIcon update / Walking...

### ISSUE THREAD

**Issue by Eric4848** [Int-one/DDogDog#59]
## 💡 Feature Issue

PetIcon에 pets를 props로 받도록 하여 사용성 증가
## 🌿  To-do

- [ ] PetIcon에서 pets를 props로 받도록 하여 사용성 증가
- [ ] petStore에서 together 추가
- [ ] together에 goWith에 해당하는 pet을 추가하는 updateTogether함수 추가
