### ISSUE TITLE
[Feat] 산책 중 페이지 구현

### ISSUE THREAD

**Issue by Eric4848** [Int-one/DDogDog#63]
## 💡 Feature Issue

산책 중 페이지를 피그마와 동일하게 구현
## 🌿  To-do

- [ ] 이전에 선택한 반려견 표시
- [ ] 반려견들의 세부 데이터 작성할 부분 표시
- [ ] 실시간 이동 거리, 시간 표시
- [ ] 산책 시작, 종료 버튼 구현
