### ISSUE TITLE
[Feat] Trade페이지 구현에 필요한 API 구현

### ISSUE THREAD

**Issue by Eric4848** [Int-one/DDogDog#65]
## 💡 Feature Issue

Trade 정보를 보여주는 페이지를 위한 API 구현
## 🌿  To-do

- [ ] 해주세요 거래 목록
- [ ] 해드려요 거래 목록
- [ ] 해주세요에 있는 반려견 정보
- [ ] 내가 지원한 해주세요 목록
