### ISSUE TITLE
[Feat] 산책 결과 페이지 구현

### ISSUE THREAD

**Issue by Eric4848** [Int-one/DDogDog#72]
## 💡 Feature Issue

피그마로 생성한 산책 결과 페이지를 구현
## 🌿  To-do

- [ ] 산책을 함께한 반려견들 표시
- [ ] 산책을 간 경로 표시
- [ ] 산책 결과 데이터 표시
