### ISSUE TITLE
[Feat] '해주세요' 목록 페이지와 상세 페이지 개선

### ISSUE THREAD

**Issue by ehanadul** [Int-one/DDogDog#74]
## 💡 Feature Issue
- '해주세요' 목록 페이지와 상세 페이지 개선

## 🌿 To-do
- [ ] '해주세요' 목록에 표시되는 카드 정보 수정.
- [ ] '해주세요' 작성 기능을 `+` 버튼으로 구현.
- [ ] Pinia 상태 관리(store)에서 데이터 연동.
- [ ] 상세 페이지에서 거래 번호와 반려견 정보 표시.
- [ ] '나의 해주세요'와 '실시간 해주세요' 목록 분리.
- [ ] 로컬스토리지의 `user_id`를 기반으로 필터링 기능 추가.
- [ ] 스타일링 및 UI 개선.
