### ISSUE TITLE
[Feat] 산책중 반려견 상세

### ISSUE THREAD

**Issue by Eric4848** [Int-one/DDogDog#80]
## 💡 Feature Issue

산책 중 반려견들을 선택해서 상세 내용을 작성할 수 있도록 한다
## 🌿  To-do

- [ ] petlog 스토어 생성
- [ ] 상세 내용을 선택한 반려견으로 설정
- [ ] 반려견 별로 상세 내용 저장
- [ ] 저장된 데이터 api로 저장
