### ISSUE TITLE
[Feat] 해주세요 거래 상세 페이지  세부 UI 구현

### ISSUE THREAD

**Issue by ehanadul** [Int-one/DDogDog#85]
## 💡 Feature Issue
해주세요 거래 상세 페이지 구현

## 🌿 To-do
- [ ] 거래 상세 페이지 레이아웃 및 UI 구성
- [ ] 거래 데이터 API 연동
- [ ] 반려견 상세 정보 표시 및 클릭 시 카드 열기/닫기 기능 구현
- [ ] 상태에 따라 거래 상태 배지 색상 변경 기능 추가
- [ ] 선택된 반려견 데이터 테이블 형식으로 표시
- [ ] 사진 클릭 시 반려견 상세 카드 on/off 기능 구현
