### ISSUE TITLE
[Fix] '해주세요' 거래 데이터 로직 개선

### ISSUE THREAD

**Issue by ehanadul** [Int-one/DDogDog#90]
## 💡 Feature Issue
- 거래 상세 페이지에서 거래 데이터를 가져오는 로직을 Pinia Store를 활용하도록 개선
- 코드의 일관성과 효율성을 높임.

## 🌿 To-do
- [ ] Pinia Store에서 거래 데이터를 로드하는 메서드 추가 (`fetchTrades`)
- [ ] `fetchTrades` 메서드를 활용해 특정 거래 데이터를 가져오도록 수정
- [ ] 기존 API 요청 코드에서 Pinia Store로의 데이터 참조 방식으로 변경
- [ ] 반려견 데이터 로드는 기존 API 요청 방식을 유지
