### ISSUE TITLE
[Feat] 시연용 더미데이터

### ISSUE THREAD

**Issue by Eric4848** [Int-one/DDogDog#92]
## 💡 Feature Issue

시연을 위한 더미 데이터 생성
## 🌿  To-do

- [ ] test@test / 1234 로 회원 생성
- [ ] 회원의 반려견 2마리 추가
- [ ] 해주세요 테이블에 요청 수정
