### ISSUE TITLE
[Feat] 해주세요 지원하기

### ISSUE THREAD

**Issue by Eric4848** [Int-one/DDogDog#95]
## 💡 Feature Issue

다른 유저가 작성한 해주세요에 지원 기능을 추가
## 🌿  To-do

- [ ] 특정 거래를 볼 떄 해당 거래에 지원한 사람을 피니아에 저장
- [ ] 지원 상태와 거래 상태를 보고 지원 버튼 구현
- [ ] 지원시 데이터베이스에 저장
